### ISSUE TITLE
The tabs Bugs and Reports remain empty

### ISSUE THREAD

**Issue by aptly-io** [F43nd1r/Acrarium#115]
Hello,
What is supposed to be shown under the bugs and reports section?
Now these remain empty while under the statistics tab there's reference on 7 reports.

Might it be related to uploading a mapping file?

Thanks!

**Comment by F43nd1r** [comment]
Reports should always show all reports. Bugs is a bit more flexible, but show something. I think #89 is related to this. Are you running acrarium on tomcat?

**Comment by aptly-io** [comment]
I run it from docker-compose (behind Traefik) inside docker image: f43nde 1r/acrarium:latest
I don't know what is inside the docker image exactly. 
Maybe that image it not in sync with the latest sources?

**Comment by aptly-io** [comment]
Found it! It's Safari related. Nice Bugs and Reports show up in Firefox and Brave! 
Sorry for the confusion.

**Comment by F43nd1r** [comment]
Ah well, not much can be done there. Although it is weird - vaadin lists safari as compatible https://vaadin.com/faq#what-technologies-does-vaadin-support
