### ISSUE TITLE
Logo/Icon

### ISSUE THREAD

**Issue by F43nd1r** [F43nd1r/Acrarium#12]
Need to create a recognizable logo and favicon.

**Comment by zuuritaly** [comment]
Hello @F43nd1r  ,
I'm a graphic designer and I design logos for open source projects.

Usually I ask the following questions to assist me in the creative process:

Do you have something in your mind for the logo?
Do you want something specific for the logo?
What colors do you want in the logo?

With your answers I will design a logo for your project and if you like it you can keep it and used.

Best Regards

Zuur

**Comment by F43nd1r** [comment]
> Do you have something in your mind for the logo?

"Acrarium" is a pun on "Aquarium", so it would be obvious to use that as a base idea. But I'd be open for other ideas too.

> Do you want something specific for the logo?

No.

> What colors do you want in the logo?

Acrarium uses the colors of the Vaadin Valo Theme (mainly #1676F4 and a bit of #FF473A). The logo should "fit in" with these colors. 
It would be great if it works on both a light and a dark background, as both themes are supported.

Currently I plan on using a logo in three locations:
1. The login page (probably above everything else) https://i.imgur.com/58Un5rg.png
2. On the Top left of every page (currently it just says "Acrarium" there) https://i.imgur.com/0b9yPxD.png
3. As a favicon (replacing the weird little crossed out bug) https://raw.githubusercontent.com/F43nd1r/Acrarium/master/src/main/resources/favicon.ico

By the way, thanks for helping out with this.

**Comment by F43nd1r** [comment]
> Hi @F43nd1r , I've designed a logo

Great work! I definetly prefer the flat style (C). 

> if you need something else please let me know

source `svg`s would be great

**Comment by mirzazulfan** [comment]
Hi @F43nd1r I've uploaded all files and created a pr. you can put my name Mirza Zulfan.

#### Licence
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

**Comment by F43nd1r** [comment]
![preview](https://imgur.com/xzFFdem.png)

Looks great!

**Comment by mirzazulfan** [comment]
Love it. Good luck with your project. :)

**Comment by F43nd1r** [comment]
Thanks, and also thanks for the design. Good luck to you too :)

**Comment by mirzazulfan** [comment]
It was my pleasure! Thank you. :100:
