### ISSUE TITLE
When are reports considered different bugs?

### ISSUE THREAD

**Issue by aptly-io** [F43nd1r/Acrarium#120]
Hello,

While playing around with an Android app causing reports to be send, I noticed that even though the Exceptions are different and also the stack trace sizes are different the bug counter still remains 1, just the report counter goes up. I would have assumed that Acrarium, when seeing different exceptions being reported, counts these as different types of defects?

I'm using the latest docker image (the about box tells me Running version 0.10.9)

**Comment by F43nd1r** [comment]
Stacktraces are considered the same if they are x% identical, where x is the configured bug matching value (95 by default).

**Comment by aptly-io** [comment]
I understand your choice as it's very tricky to come up with an algorithm that would be more accurate.

On a Galaxy/Android-10, 2 different exception but with an otherwise almost identical stack trace were seen as identical.

On the other hand, the same 2 defects, one coming from an LG G5/Android-8 and the other from a Galaxy/Android-10 were seen as different.

Of course the defects were inflicted hence a bit artificial, in a real app likely these side effects occur less.

**Comment by F43nd1r** [comment]
Yeah, in the end whatever algorithm you choose, you'll end up with some manual work. You can also basically disable this feature by setting the matching value to 100.

>On the other hand, the same 2 defects, one coming from an LG G5/Android-8 and the other from a Galaxy/Android-10 were seen as different.

Different Vendors often implement android differently, leading to vastly different stacktraces. Not much to be done in this case.

**Comment by timbze** [comment]
> Stacktraces are considered the same if they are x% identical, where x is the configured bug matching value (95 by default).

Would you be able to add something like this to the setting description? I couldn't figure out what the "Score" meant so I came here to search and see if I could find it.
