### ISSUE TITLE
Are app's notifications saved/persistant?

### ISSUE THREAD

**Issue by aptly-io** [F43nd1r/Acrarium#124]
Hello,
I have an admin and user account (not sure if this might be related) and logged-in as the user.
I added a new app.
I go to the Admin tab for the app.
I check all 4 the notifications.
When I leave this view and come back later, all checkboxes are unchecked.
I'm not sure if these notifications are active or not and its just the state that's not reflected correctly.
Thanks

**Comment by F43nd1r** [comment]
It's a purely visual bug

**Comment by aptly-io** [comment]
Thanks!
