### ISSUE TITLE
Notification settings are not getting saved

### ISSUE THREAD

**Issue by HulakOleksandr** [F43nd1r/Acrarium#141]
Hi!

I was trying to apply different settings in Acrarium and found that if I open some App, go to Admin panel and check/uncheck something in Notifications panel, the value is not getting saved. When I reopen / reload the page, all the settings are unchecked.

**Comment by HulakOleksandr** [comment]
Saw a related change in the latest change log :)

**Comment by F43nd1r** [comment]
> Saw a related change in the latest change log :)

Yeah, duplicate of #124
