### ISSUE TITLE
Default standalone upload file size limit is too small for mapping.txt

### ISSUE THREAD

**Issue by mikedawson** [F43nd1r/Acrarium#147]
Hi,

Acrarium is a great way to manage reports without sending everyone's data to various proprietary clouds. When you try and upload mapping.txt the default size limit is 1MB, which is far too small. I was able to fix this by adding these lines to application.properties

```
spring.servlet.multipart.max-request-size=50MB

spring.servlet.multipart.max-file-size=50MB
```

I think it would be good to include these lines in any example application.conf in the Wiki setup guide.

**Comment by andreas-borglin** [comment]
We had the same problem and solved it by adding these to the environment section in the docker compose file.
```
SPRING_SERVLET_MULTIPART_MAXFILESIZE: 100MB
SPRING_SERVLET_MULTIPART_MAXREQUESTSIZE: 100MB
```

**Comment by F43nd1r** [comment]
I've increased the default values to 100mb. If you still feel like this should be documented you're free to edit the wiki.

**Comment by mikedawson** [comment]
:+1:  Thank you! I think if those defaults apply, there's no need to add to the documentation.
