### ISSUE TITLE
Use APP_VERSION_NAME as App version

### ISSUE THREAD

**Issue by ms502040** [F43nd1r/Acrarium#148]
Hi,
in statistics and report sumary  you using APP_VERSION_NAME as App version but in Bugs and Reports tabs APP_VERSION_CODE. 
or make it configurable or use APP_VERSION_NAME at all.
I`m using APP_VERSION_CODE as build number (and not only me) and if filter < and > not working.

**Comment by F43nd1r** [comment]
I'm using the `versionCode` in places where you can sort by version, because sorting `versionsName`s lexicographically makes a lot less sense than sorting by the monotonically increasing `versionCode`.

**Comment by ms502040** [comment]
versionsName increased as well as version code see: https://en.wikipedia.org/wiki/Software_versioning

**Comment by F43nd1r** [comment]
Not everybody uses the same versioning scheme, it is impossible to write a function to handle them all correctly.
