### ISSUE TITLE
Missing version code on some reports

### ISSUE THREAD

**Issue by zx2c4** [F43nd1r/Acrarium#16]
Some reports have an empty version name and code:

![image](https://user-images.githubusercontent.com/10643/43258618-b8745de0-90d3-11e8-9219-f7e3743452fa.png)

That results in 0 as the version in the main view, which is confusing:

![image](https://user-images.githubusercontent.com/10643/43258652-cece5974-90d3-11e8-9ebb-4ab873f19259.png)

However, that very same report does have a happy `BUILD_CONFIG` section (thanks to me supplying `buildConfigClass = BuildConfig.class` in `@AcraCore`):

![image](https://user-images.githubusercontent.com/10643/43258699-edaf364c-90d3-11e8-8039-33dc9763c174.png)

I'm not sure why this report doesn't have `APP_VERSION_*` filled in; perhaps it's due to something awful on the part of the user's OS. Or perhaps it couldn't be parsed by Acrarium? However, if it's the first case, it would be smart to _fallback_ to using `BUILD_CONFIG` in the event that `APP_VERSION_*` are missing, for populating the actual version column of each report.

**Comment by zx2c4** [comment]
```java
            Stacktrace stacktrace = findStacktrace(generifiedStacktrace).orElseGet(() -> new Stacktrace(findBug(app, generifiedStacktrace).orElseGet(() -> new Bug(app,
                    generifiedStacktrace)),
                    generifiedStacktrace,
                    jsonObject.optInt(ReportField.APP_VERSION_CODE.name()),
                    jsonObject.optString(ReportField.APP_VERSION_NAME.name())));
```

In otherwords, just have the last two lines here take the fallback parameter to optInt/optString that cascades down to ReportField.BUILD_CONFIG....

**Comment by F43nd1r** [comment]
Due to the issues noted in [ACRA](https://github.com/ACRA/acra/blob/master/acra-core/src/main/java/org/acra/util/PackageManagerWrapper.java#L76) I think just using the BuildConfig as default if it is available seems like the better idea.

**Comment by zx2c4** [comment]
Sure, makes sense.
