### ISSUE TITLE
Impossible to solve a bug

### ISSUE THREAD

**Issue by martynamaron** [F43nd1r/Acrarium#161]
I'm not able to solve a bug in Acrarium - whenever I select the app version where the crash was fixed, my selection disappears soon after - evidence below. Is there a different (correct?) way of solving a bug in Acrarium which I'm just not aware of? 👀 

We're running the v1.0.2 Acrarium in a Docker container (f43nd1r/acrarium:1.0.2)

![Acrarium-solve-bug](https://user-images.githubusercontent.com/6472748/98811508-e08bb780-2418-11eb-8bd6-eedf2e236470.gif)

**Comment by F43nd1r** [comment]
> Is there a different (correct?) way of solving a bug in Acrarium which I'm just not aware of?

No, this is the correct way.

I couldn't reproduce the issue. Is there any message/exception in the logs?

**Comment by martynamaron** [comment]
I have found some exceptions in the logs that look relevant, yes - attached (the exception is really long) 
[Acrarium solve bug exception](https://github.com/F43nd1r/Acrarium/files/5545484/acrarium-solve-bug-log.txt)

The exception:
```
java.lang.IllegalStateException: Multiple representations of the same entity [com.faendir.acra.model.App#5] are being merged. Detached: [com.faendir.acra.model.App@5]; 
Detached: [com.faendir.acra.model.App@5]
```

Further down the stack trace there's a relevant line:
`at com.faendir.acra.service.DataService.setBugSolved(DataService.kt:173) ~[classes/:1.0.2]`

I have noticed that there are some crashes that I'm able to filter (although a minority) - the app version remains set, and those bugs are filtered out from the full list, unlike the screen recording above.

Is this a problem in the database again? :(

**Comment by F43nd1r** [comment]
Try again with 1.0.3, should be out soon.

> Is this a problem in the database again? :(

No.

**Comment by martynamaron** [comment]
Apologies for the delay in replying - we've verified with the 1.0.3 version and it's working as expected now, thank you! Closing this issue then.
