### ISSUE TITLE
Support receive data from app ?

### ISSUE THREAD

**Issue by MarkMjw** [F43nd1r/Acrarium#164]
How to accept the data sent by the app, don't find api in wiki.

**Comment by F43nd1r** [comment]
What?

**Comment by MarkMjw** [comment]
Sorry,  i found this api: http://xxx:xx/report
but,  it's return 403. however access to /api/apps is correct.

**Comment by F43nd1r** [comment]
That endpoint is for Acra. If you create an app in acrarium you'll get a
configuration which is authorised for it.

**Comment by MarkMjw** [comment]
It's ok, thanks very much.
