### ISSUE TITLE
Display problem of Chinese.

### ISSUE THREAD

**Issue by MarkMjw** [F43nd1r/Acrarium#167]
The log contains Chinese, but it cannot be displayed.
![image](https://user-images.githubusercontent.com/4126838/99770904-2ea06980-2b43-11eb-914e-a544ad0e6833.png)

**Comment by F43nd1r** [comment]
- is this a display issue or are the characters missing in the database?

- which browser are you using?

I'm not sure I'll be able to fix this, as none of my browsers display chinese characters correctly.
