### ISSUE TITLE
Send a report with postman

### ISSUE THREAD

**Issue by Farzad-Aghaeizadeh** [F43nd1r/Acrarium#183]
I have installed Acrarium in my server, created an application and want to connect Acra Android to Acrarium, but no crash log has been submitted, so I want to know how can I sent a fake crash request - custom log in my Acrarium server with postman and see the result.

**Comment by F43nd1r** [comment]
ACRA reports are POSTed to the server with http basic auth. You can extract a sample report from your apps data folder. If there are none, turn internet off and crash again.
