### ISSUE TITLE
Acrarium not showing crash logs

### ISSUE THREAD

**Issue by Farzad-Aghaeizadeh** [F43nd1r/Acrarium#184]
Hello dear Acrarium,
When I start the docker compose I see this error :

`acrarium    | java.util.ServiceConfigurationError: org.hibernate.boot.spi.MetadataBuilderInitializer: Provider com.faendir.acra.hibernate.ZonedDateTimeMetadataBuilderInitializer not found
acrarium    | 	at java.base/java.util.ServiceLoader.fail(Unknown Source) ~[na:na]
acrarium    | 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(Unknown Source) ~[na:na]
acrarium    | 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(Unknown Source) ~[na:na]
acrarium    | 	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(Unknown Source) ~[na:na]
acrarium    | 	at java.base/java.util.ServiceLoader$2.hasNext(Unknown Source) ~[na:na]
acrarium    | 	at java.base/java.util.ServiceLoader$ProviderSpliterator.tryAdvance(Unknown Source) ~[na:na]
acrarium    | 	at java.base/java.util.Spliterators$1Adapter.hasNext(Unknown Source) ~[na:na]
acrarium    | 	at org.hibernate.boot.registry.classloading.internal.AggregatedServiceLoader$ClassPathAndModulePathAggregatedServiceLoader.hasNextIgnoringServiceConfigurationError(AggregatedServiceLoader.java:241) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.boot.registry.classloading.internal.AggregatedServiceLoader$ClassPathAndModulePathAggregatedServiceLoader.loadAll(AggregatedServiceLoader.java:219) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.boot.registry.classloading.internal.AggregatedServiceLoader$ClassPathAndModulePathAggregatedServiceLoader.getAll(AggregatedServiceLoader.java:187) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.loadJavaServices(ClassLoaderServiceImpl.java:251) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.boot.internal.MetadataBuilderImpl.<init>(MetadataBuilderImpl.java:139) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.boot.MetadataSources.getMetadataBuilder(MetadataSources.java:141) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:238) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:168) ~[hibernate-core-5.4.23.Final.jar:5.4.23.Final]
acrarium    | 	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:52) ~[spring-orm-5.3.1.jar:5.3.1]
acrarium    | 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365) ~[spring-orm-5.3.1.jar:5.3.1]
acrarium    | 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[spring-orm-5.3.1.jar:5.3.1]
acrarium    | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
acrarium    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
acrarium    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
acrarium    | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]`

but the dashboard is working and I created new app.
in acra android the library is connecting and working good, it says that request has been sent and received response code 200

`D/ACRA: Connect to http://xxx.xxx.xxx.xxx:9000/
D/ACRA: Checking plugin Configurations : ImmutableList{[org.acra.config.HttpSenderConfiguration@ad681c5]} for class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Checking plugin Configuration : org.acra.config.HttpSenderConfiguration@ad681c5 against plugin class : class org.acra.config.HttpSenderConfiguration
D/ACRA: Sending request to http://xxx.xxx.xxx.xxx:9000/
D/ACRA: Request response : 200 : 
I/ACRA: Request received by server
D/ACRA: Sent report using org.acra.sender.HttpSender
D/ACRA: Report was sent by all senders
D/ACRA: Finished sending reports from SenderService`

but after acra said request received by server, the server generates this log and didn't submit crash :

`acrarium    | OS major version parsing failed for: acra 5 For input string: "acra 5"
acrarium    | OS major version parsing failed for: acra 5 For input string: "acra 5"
acrarium    | OS major version parsing failed for: acra 5 For input string: "acra 5"
acrarium    | OS major version parsing failed for: acra 5 For input string: "acra 5"
acrarium    | OS major version parsing failed for: acra 5 For input string: "acra 5"
`

**Comment by F43nd1r** [comment]
> When I start the docker compose I see this error

See https://github.com/F43nd1r/Acrarium/issues/100#issuecomment-672931568

> but after acra said request received by server, the server generates this log and didn't submit crash 

According to https://github.com/ACRA/acra/issues/774 it might be a wrong uri. Check your acra config.

**Comment by mtangoo** [comment]
@F43nd1r can you have a look at #189? It is the same thing, almost the same but with minor difference
