### ISSUE TITLE
Cannot see Bug or Report

### ISSUE THREAD

**Issue by mtangoo** [F43nd1r/Acrarium#189]
So I created the instance using Docker Compose and apart from little warning it is running.
I created an app, took credentials and tried to post using Insomnia directly (A bug report sent from actual phone as JSON). 
It showed that the bug was recorded. see the image below

<img width="1440" alt="Screen Shot 2021-01-09 at 10 36 45" src="https://user-images.githubusercontent.com/1502872/104087102-689e0a00-526e-11eb-849a-4f21ca190a05.png">

Then I clicked the app to see the reports and everything is empty like image shows

<img width="1440" alt="Screen Shot 2021-01-09 at 10 37 20" src="https://user-images.githubusercontent.com/1502872/104087122-85d2d880-526e-11eb-8fef-5b571ad6cfce.png">

What is wrong with my installation? Anything to check?

No error is reported when I send the POSt request nor when I try to access the bugs by clicking on the app

**Comment by mtangoo** [comment]
Dupe of #184

**Comment by mtangoo** [comment]
Checked the reports by selecting the date I get the charts with correct information(Mobile Phone Model, App version, et al), which means data is stored. But cannot get it displayed.

I have reopened because I believe issue might be different from referenced issue!

**Comment by F43nd1r** [comment]
Have you checked #89 and #115?
