### ISSUE TITLE
JSONObject["REPORT_ID"] not found

### ISSUE THREAD

**Issue by akoua** [F43nd1r/Acrarium#194]
I connect with my flutter App, so I get this error on Acrarium server stacktrace:

`acrarium | Hibernate: select bug1_.`id` as id1_2_0_, version2_.`id` as id1_10_1_, bug1_.`app_id` as app_id3_2_0_, bug1_.`solved_version` as solved_v4_2_0_, bug1_.`title` as title2_2_0_, version2_.`app_id` as app_id5_10_1_, version2_.`code` as code2_10_1_, version2_.`name` as name4_10_1_ from `stacktrace` stacktrace0_ inner join `bug` bug1_ on stacktrace0_.`bug_id`=bug1_.`id` left outer join `version` version2_ on bug1_.`solved_version`=version2_.`id` where bug1_.`app_id`=? and (stacktrace0_.`stacktrace` like ? escape '!') limit ?

acrarium    | Hibernate: insert into `bug` (`app_id`, `solved_version`, `title`) values (?, ?, ?)
acrarium    | Hibernate: insert into `version` (`app_id`, `code`, `mappings`, `name`) values (?, ?, ?, ?)
acrarium    | Hibernate: insert into `stacktrace` (`bug_id`, `stacktrace`, `version_id`) values (?, ?, ?)
acrarium    | 2021-01-13 16:33:05.403 ERROR 1 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.json.JSONException: JSONObject["REPORT_ID"] not found.] with root cause

acrarium    | acrarium    | org.json.JSONException: JSONObject["REPORT_ID"] not found.
acrarium    |   at org.json.JSONObject.get(JSONObject.java:573) ~[json-20190722.jar:na]
acrarium    |   at org.json.JSONObject.getString(JSONObject.java:836) ~[json-20190722.jar:na]
acrarium    |   at com.faendir.acra.model.Report.<init>(Report.kt:65) ~[classes/:1.1.0]
acrarium    |   at com.faendir.acra.service.DataService.createNewReport(DataService.kt:315) ~[classes/:1.1.0]
acrarium    |   at com.faendir.acra.service.DataService$$FastClassBySpringCGLIB$$c0f33e7.invoke(<generated>) ~[classes/:1.1.0]
acrarium    |   at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.2.jar:5.3.2]
acrarium    |   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.2.jar:5.3.2]`

**Comment by F43nd1r** [comment]
You acra report content must include `REPORT_ID`

**Comment by akoua** [comment]
How can I include REPORT_ID ?

**Comment by F43nd1r** [comment]
https://www.acra.ch/javadoc/5.6.2/org/acra/annotation/AcraCore.html#reportContent--

**Comment by akoua** [comment]
Thanks
