### ISSUE TITLE
@AcraHttpSender change

### ISSUE THREAD

**Issue by savenko-egor** [F43nd1r/Acrarium#196]
Hello!

Please specify how I can change options "@AcraHttpSender" if I run Acrarium from docker-compose?

Best regrads.

**Comment by F43nd1r** [comment]
What? That is acra configuration, it has nothing to do with your acrarium hosting.

**Comment by savenko-egor** [comment]
When I create application I got this code:
`@AcraCore(reportFormat = StringFormat.JSON)`
`@AcraHttpSender(uri = "localhost:8080/report" /*best guess, you may need to adjust this*/,`
`basicAuthLogin = "...",`
`basicAuthPassword = "...",`
`httpMethod = HttpSender.Method.POST)`
I can change "localhost:8080/report" on "https://my.domain.com/report"?

**Comment by F43nd1r** [comment]
If your docker container is exposed on port 80 or 443, yes. Otherwise your url has to include a port.

**Comment by savenko-egor** [comment]
Sorry. My bad english broken all my words)
I need to change this so that when I create a new application I got message with my URL.
I can make this?

**Comment by F43nd1r** [comment]
I'm sorry, I don't understand the question.

**Comment by savenko-egor** [comment]
Sorry this is my trouble. I will try explain with screenshots.
If I create new app in Acrarium I got this message:
![Screenshot_20210120_001332](https://user-images.githubusercontent.com/38104662/105099447-62046380-5ab4-11eb-92e2-73b31f46be15.png)
But I want this:
![Screenshot_20210120_001307](https://user-images.githubusercontent.com/38104662/105099527-7fd1c880-5ab4-11eb-851b-2bd561be0533.png)
Can I change env variable for got this?

**Comment by F43nd1r** [comment]
You don't need to do anything, Acrarium works on all domains your host supports.
This configuration is only shown to you to help you with configuring acra. You can change those values in your acra configuration.

**Comment by savenko-egor** [comment]
I understand it.
But I will need manual change this URL in my program code on my Acrarium URL. But if this URL can be changed in Acrarium i will econymy my time. And your. I think =)

**Comment by F43nd1r** [comment]
set `SERVER_CONTEXTPATH=domain.com`

**Comment by savenko-egor** [comment]
I tried set `SERVER_CONTEXTPATH: my.domain.com` in docker-compose.yml and restart container but this not works for me.
In logs I see:
`Tomcat started on port(s): 8080 (http) with context path ''`

**Comment by F43nd1r** [comment]
That is expected. Please explain what you're actually trying to achieve with this change.

**Comment by savenko-egor** [comment]
For copy&paste this code from Acrarium page on my source code without any change. Only this.

Thank you. And sorry for my stupid explains =)

**Comment by savenko-egor** [comment]
I have not specified what I am using nginx for proxy all requests from my.domain.com:443 to locahost:8080. And nginx used for allow access from access list.
Code from nginx conf:
`...`
`location / {`
`        include acl.conf;`
`        proxy_pass http://localhost:8080;`
`        limit_req   zone=lreq  burst=7;`
`}`

`location /report {`
`        proxy_pass http://localhost:8080;`
`        limit_req   zone=lreq  burst=7;`
`}`
`...`

**Comment by F43nd1r** [comment]
proxy_pass http://localhost:8080/report; maybe? I don't use nginx.

**Comment by savenko-egor** [comment]
No. In configuration nginx all good and all works. I specified it for you can see what access to Acrarium from nginx.
I see in source code you getting URL from header "host". I think you need added condition if env SERVER_URL (for example) not null use him, if null, try to get URL from headers.

**Comment by F43nd1r** [comment]
You need `proxy_set_header Host my.domain.com;` according to https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/#passing-request-headers

**Comment by savenko-egor** [comment]
Yes. This can changed headers, but if I set `proxy_set_header Host 'https://my.domain.com';` I got 400 error.
Why don't you want to add the ability to change it via ENV? Or do you think that not everyone needs it? If this true, I'll just close this issue.
