### ISSUE TITLE
Use utf8mb4 for databases

### ISSUE THREAD

**Issue by otbutz** [F43nd1r/Acrarium#204]
The [documentation](https://github.com/F43nd1r/Acrarium/wiki/Configure-existing-database#1-create-a-new-mysql-database-and-user) instructs to create a database with characterset `utf8`. This is not recommended for mysql databases as only `utf8mb4` provides *real* UTF8.

See https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434

**Comment by F43nd1r** [comment]
I've updated the documentation.

Regarding the linked article: There is some good info in there, however the first two takeaway points are just plain unrelated hate against databases by the author. The third one lists a better article which includes much of the same info plus an upgrade path if you created databases with utf8mb3 before. https://mathiasbynens.be/notes/mysql-utf8mb4#utf8-to-utf8mb4
