### ISSUE TITLE
ProGuard Mappings Upload Success but the Icon Still 'X'

### ISSUE THREAD

**Issue by JessicaClarisa** [F43nd1r/Acrarium#215]
Hello,

I tried uploading ProGuard's mapping.txt file. Then I click 'Save' but the icon still 'X'. 
I tried reloading the page but still no change.
What should I do?

![mapping1](https://user-images.githubusercontent.com/41095168/110081117-0a009280-7dbe-11eb-953a-bae49d388fa2.PNG)
![mapping2](https://user-images.githubusercontent.com/41095168/110081122-0b31bf80-7dbe-11eb-8f01-77125341161c.PNG)

**Comment by F43nd1r** [comment]
What's your acrarium version?

**Comment by JessicaClarisa** [comment]
It's 1.1.0

**Comment by F43nd1r** [comment]
Possibly. Did you check the server log?

**Comment by JessicaClarisa** [comment]
Yes, it turns out my .txt file is too big.
I add this in my docker-compose.yml under database service:
`command: --max_allowed_packet=20342374`

It solves the problem.
Thank you.
