### ISSUE TITLE
Request: Add Custom Column for Filtering

### ISSUE THREAD

**Issue by JessicaClarisa** [F43nd1r/Acrarium#221]
Hello,

It would be nice if we can add a new column in Reports dashboard in case there's other important data to filter.
Specific case example: add new optional column for Brand and I can modify the brand information there to suit my needs.

Thank you.

**Comment by F43nd1r** [comment]
Needs design: Current columns correspond to database columns and rely on that for sorting/filtering. Fixed number of custom columns in database maybe?

**Comment by JessicaClarisa** [comment]
Yes. One or two is enough (two if possible, but one is already very helpful).
