### ISSUE TITLE
Request: Display device marketing name & filter silent exceptions

### ISSUE THREAD

**Issue by r748** [F43nd1r/Acrarium#222]
Hello

Thank you for your work!

Currently Acrarium shows the device model name, for example VOG-L29, which is very cryptic. It would be great to also have the marketing name (in this case Huawei P30 Pro) visible at first glance. The info could be derived from this list: [https://storage.googleapis.com/play_public/supported_devices.html](https://storage.googleapis.com/play_public/supported_devices.html).

Also, it would be great to have an option to show/hide silent exceptions, in order to have a better overview over critical and non-critical reports.

Thanks.

**Comment by F43nd1r** [comment]
> The info could be derived from this list: https://storage.googleapis.com/play_public/supported_devices.html.

Is there any license or user agreement attached to that API?

**Comment by r748** [comment]
Well, it's not an API, it's the official listing of Google Play supported devices, published by Google. As far as I can see, there are no license restrictions implied. There is also a small Android Library ([https://github.com/jaredrummler/AndroidDeviceNames](https://github.com/jaredrummler/AndroidDeviceNames)) which uses the data.
