### ISSUE TITLE
Documention enhancement - setup guide for free/lite tier on IBM / bluemix

### ISSUE THREAD

**Issue by mikehardy** [F43nd1r/Acrarium#23]
This is a friendly request for a setup guide similar to acralyzer that shows step by step how to set up Acrarium on the lite (free forever) plan in IBM's bluemix cloud system

My reasoning here is I'm not aware of any other professional grade free hosting plans like this that would allow people to try out a Java+SQL app, and you can also scale it out with them if you need to later.

If this were possible I could try to use Acrarium as the back-end for a couple apps vs acralyzer (which I'm using now, and know how to setup after reading their cloudant setup guide)

As with all enhancement requests, feel free to either completely ignore this or summarily close it as won't-fix at your option :-)

**Comment by F43nd1r** [comment]
I am unable to find any free option to add an sql database in bluemix. Are you sure their free plan fulfills the requirements for Acrarium?

**Comment by mikehardy** [comment]
Hmm - SQL was in "the area" (in quotes because I admit it's vague) of documentation around lite plans but I will admit I didn't try it personally, so I'm only a little surprised if it just isn't possible. That begs the question then of whether it's possible anywhere to set up a personal demo on a host, even for open source apps (which have more free hosting options). May just not be possible.

**Comment by F43nd1r** [comment]
Bluemix certainly is no option. I've just performed some more tests, and Acrarium can't start on the 256MB memory which is the maximum in the free tier.

I've always tested locally, and my production instance is deployed on a small vServer, which costs like 3€ a month.

In general: Acrarium is not intended to be a drop-in replacement for acralyzer.
Acralyzers main goal was simplicity both in setup and usage, while Acrarium aims for feature-richness.
