### ISSUE TITLE
Proguard editing buttons not visible in Firefox

### ISSUE THREAD

**Issue by otbutz** [F43nd1r/Acrarium#245]
Version: 1.3.0 but was also broken in 1.2.1

Chrome:

![grafik](https://user-images.githubusercontent.com/22315436/115676328-c6eb8600-a34f-11eb-9cb9-383583a19d1c.png)

Firefox:

![grafik](https://user-images.githubusercontent.com/22315436/115676403-da96ec80-a34f-11eb-8cc1-a0c2a9b4fb6c.png)

I can click the buttons but they are invisible in Firefox.

**Comment by otbutz** [comment]
They show up if i change to column widths in Firefox.

**Comment by F43nd1r** [comment]
I'm aware of this issue and have reported it upstream https://github.com/vaadin/vaadin-grid/issues/2152

**Comment by F43nd1r** [comment]
You can thumb up the upstream issue to indicate you're impacted by the issue. That might up its priority for the folks at vaadin.

**Comment by otbutz** [comment]
Done. I also added a comment: https://github.com/vaadin/vaadin-grid/issues/2152#issuecomment-828251847
