### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by wbrawner** [F43nd1r/Acrarium#25]
Having a REST API in addition to the web interface would be nice for building automated monitoring solutions or even a mobile app or something to help access the data a little easier from places other than a web browser

**Comment by wbrawner** [comment]
P.S. I can help with this if needed

**Comment by F43nd1r** [comment]
Are you talking about an interface to get the report json, or an did you have full database access in mind?

**Comment by wbrawner** [comment]
I'm thinking full database access, so that for example I could make a request to get the number of issues for a given time period and send out an alert if it exceeds a given threshold or periodically query the server to see if there are new issues that haven't been seen before.

**Comment by wbrawner** [comment]
Though being able to retrieve individual issue report JSON could also be helpful

**Comment by F43nd1r** [comment]
I've added a [basic interface](https://github.com/F43nd1r/Acrarium/blob/master/src/main/java/com/faendir/acra/rest/RestApiInterface.java). It allows read-only access to all available content. You'll need to grant a  user API access in the user manager (the default user cannot have api access).
You may open a pull request with additional methods if you need them.

**Comment by wbrawner** [comment]
Hey, this looks great, thanks! I'll have a look this weekend and play around with it. I appreciate it!
