### ISSUE TITLE
Edit config path

### ISSUE THREAD

**Issue by karelkryda** [F43nd1r/Acrarium#264]
Hi, I need change ${user.home} to ${HOME}. I'm using Pterodactyle with Java egg. Is it possible? Thanks

**Comment by F43nd1r** [comment]
Use some other form of [externalized configuration](https://docs.spring.io/spring-boot/docs/2.5.0/reference/html/features.html#features.external-config) for nonstandard environments, e.g. `SPRING_APPLICATION_JSON`

**Comment by karelkryda** [comment]
@F43nd1r but I need edit file in .jar or not?

**Comment by F43nd1r** [comment]
Read what I linked. You can use environment variables or system properties.

**Comment by karelkryda** [comment]
@F43nd1r so I should do smth like this?
`java -jar acrarium.jar --user.home="/home/container"`

**Comment by F43nd1r** [comment]
`-Duser.home=`
