### ISSUE TITLE
Columns are stretched too much if report contains long lines

### ISSUE THREAD

**Issue by gmk57** [F43nd1r/Acrarium#272]
When a report contains some long lines (e.g. from logcat), value columns for tabular data (BUILD, BUILD_CONFIG, CRASH_CONFIGURATION, etc) are stretched far beyond the right edge of the screen, making them rather hard to use.

![image](https://user-images.githubusercontent.com/22061463/120800397-8e42ed00-c548-11eb-9e09-70f570ffeb75.png)

**Comment by F43nd1r** [comment]
This issue was fixed before in 81de1ac0b525dc3513301811410af230c1f20586, which is in 1.3 and 1.4, please confirm you're not using an old version

**Comment by gmk57** [comment]
Yes, we were using an older version and upgrading to 1.4 fixed the issue. Thanks!
