### ISSUE TITLE
Can't see default config values with Kotlin DSL

### ISSUE THREAD

**Issue by gmk57** [F43nd1r/Acrarium#273]
Thanks for the great library!

We recently updated ACRA to 5.8 and switched to Kotlin DSL for its configuration.

Everything works great, but we can't see default config values anymore, neither in the source code (there seems to be no source code for e.g. `CoreConfigurationBuilder`), nor [in the docs](http://www.acra.ch/javadoc/latest/acra/org.acra.config/-core-configuration-builder/index.html).

With the old config system default values were visible right inside the annotation class.

**Comment by F43nd1r** [comment]
> there seems to be no source code for e.g. CoreConfigurationBuilder

These classes are generated. They're not available in this repo, but can be found in the distributed archive.

> With the old config system default values were visible right inside the annotation class.

We are in a transitional period where annotations are deprecated but still available. They remain the single source of truth, which means you can still look up the respective annotation. Alternatively, you can look at the `init` block of `<module>ConfigurationBuilder`

This should improve with ACRA 5.9, which will remove annotations and move the default value definitions.
