### ISSUE TITLE
[HELP] Nginx with reverse proxy to tomcat : 404

### ISSUE THREAD

**Issue by Shabinder** [F43nd1r/Acrarium#283]
I set up reverse proxy as following :
```
location /acrarium/ {
                proxy_pass http://127.0.0.1:3201/acrarium/;
        }
```
But when accessing , static files as : 
`/var/www/html/acrarium/VAADIN/build/vaadin-bundle-5a920a83a2777ea85332.cache.js`
![image](https://user-images.githubusercontent.com/44765050/121798398-ad760480-cc43-11eb-86d6-828d81cf732d.png)

`[error] 3619#3619: *81 open() "/var/www/html/acrarium/VAADIN/build/vaadin-bundle-5a920a83a2777ea85332.cache.js" failed (2: No such file or directory)`

Accessing directly http://127.0.0.1:3201/acrarium/ works

**Comment by F43nd1r** [comment]
I don't know much about nginx, but here's how I do it with apache. Maybe it helps
<VirtualHost *:443>
    ServerName acrarium.mydomain.com
    ProxyPass  / http://localhost:8080/
    ProxyPassReverse / http://localhost:8080/
    ProxyPassReverseCookiePath / /
</VirtualHost>

**Comment by timbze** [comment]
This is how I use Nginx, and it works:
```
        location / {
                proxy_pass              http://localhost:8079/;
                proxy_set_header        Host $host;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto $scheme;
        }

        client_max_body_size 50M;
```

I use the `client_max_body_size` so that my attachments that are bigger than 1 or 2Mb (nginx default) will upload.
