### ISSUE TITLE
[Bug] Login Autofilling by Password Manager

### ISSUE THREAD

**Issue by cs8898** [F43nd1r/Acrarium#290]
# The Problem

When filling out the login form with my PasswordManager i can't login (auto Submitting the form)
But when filling out without the autosubmit and Pressing any of the possible submit ways (via Enter and via Button) all workes fine.

## Used  PW Manager and Browser

* PassFF 1.11.2
* Firefox 90.0.2

## Possible Reasons

* AFAIK Vaadin can have AJAX Forms or stuff like that, probably the BrowserPlugins handles an direct Form submit...

## Further Investigation needed

* I will check it in the next weeks

Just wanted to tell you about it...

**Comment by F43nd1r** [comment]
From personal experience I know there are password manager plugins which do work with this form (namely KeePassXC-Browser), maybe also file the issue on PassFF side?

**Comment by cs8898** [comment]
Ah thanks for the hint.
I will check that also.

Am 30. Juli 2021 11:08:20 MESZ schrieb F43nd1r ***@***.***>:
>From personal experience I know there are password manager plugins
>which do work with this form (namely KeePassXC-Browser), maybe also
>file the issue on PassFF side?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/F43nd1r/Acrarium/issues/290#issuecomment-889754078

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
