### ISSUE TITLE
Change entries (links) so they can open in new tab

### ISSUE THREAD

**Issue by timbze** [F43nd1r/Acrarium#293]
I often use the mouse middle-button click to open a link in a new tab, but the way that bug reports are showing, it's not possible.

Would it be possible to change the bug line entries to a type of link that could be middle-clicked? Or right-clicked and have the option "Open link in new tab".

**Comment by F43nd1r** [comment]
Unfortunately this is not possible in vaadin flow. I've raised the [relevant issue](https://github.com/vaadin/flow-components/issues/1305) 3 years ago, so I don't expect this to change.

**Comment by timbze** [comment]
Ok. I haven't used vaadin at all, but in other similar frameworks I have used a different component for 1 specific column. For example, you have a dropdown in "Solved" column. 

Would it be possible to change the "Title" column to be a link `<a>` component? That would just turn the text into a regular link.

**Comment by F43nd1r** [comment]
Added a button to open in new tab in 15387fe76c45880150a22bbe18318de87cbb795d
