### ISSUE TITLE
Acrarium can't connect to MySQL

### ISSUE THREAD

**Issue by bulldozer75** [F43nd1r/Acrarium#298]
If I use your docker-compose.yml without any changes, then the acrarium container can't connect to the MySQL instance during the first start.
The error is
```java.sql.SQLException: Access denied for user 'acrarium'@'172.20.0.3' (using password: YES)```

It doesn't help if I change the passwords.

If I connect from the host (need to expose the port beforehand), there is still "Access denied error":
```mysql -u root -p'[[root_password]]' -h localhost -P 3306 --protocol=tcp```

```
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'172.20.0.1' (using password: YES)
```

I think there is something with the MySQL configuration. I'm not an expert in this.

[acrarium.log](https://github.com/F43nd1r/Acrarium/files/7080894/acrarium.log)

Ubuntu 20.04.3 LTS
Docker version 20.10.8, build 3967b7d
docker-compose version 1.29.2, build 5becea4c

**Comment by F43nd1r** [comment]
Make sure that user actually exists in that database with the given password and has access to the database

**Comment by bulldozer75** [comment]
Oh, thanks. I thought that the script would do that work for me. It's worth to mention that you need to create the user manually.

**Comment by F43nd1r** [comment]
https://github.com/F43nd1r/Acrarium/wiki/Configure-existing-database
