### ISSUE TITLE
Can't start Acrarium after pulling latest versionof Docker image: 'Could not find or load main class ${JAVA_OPTS}'

### ISSUE THREAD

**Issue by christophehenry** [F43nd1r/Acrarium#299]
#291 tried to introduce the possibility to pass `JAVA_OPTS` to Docker. As far as I understand it, Dockerfile's `ENTRYPOINT` doesn't perform variable interpolation as is.  You need to use `bin/sh -c` as mentionned in [this Stakcoverflow thread](https://stackoverflow.com/a/42332740).

I would happily confirm the fix on my server and open a PR if someone provides me the steps to build the Dockerfile.

**Comment by F43nd1r** [comment]
Fixed in 1.6.1

**Comment by christophehenry** [comment]
Oh, that was quick. Nice, thank you!
