### ISSUE TITLE
db initialization failed : can not create view

### ISSUE THREAD

**Issue by helinyun98** [F43nd1r/Acrarium#3]
Changlog 34 & 35 has specific database name ‘acra’, initialization will  failed when database has difference name.

[ost-startStop-1] liquibase                                : classpath:/db/changelog/db.changelog-master.yaml: classpath:/db/changelog/db.changelog-master.yaml::1527006878002-34::lukas (generated): Change Set classpath:/db/changelog/db.changelog-master.yaml::1527006878002-34::lukas (generated) failed.  Error: ANY command denied to user 'usr_android'@'%' for table 'app' [Failed SQL: CREATE VIEW android_log.app_view AS (select `acra`.`app`.`id` AS `id`,`acra`.`app`.`name` AS `name`,count(`acra`.`report`.`id`) AS `report_count` from ((`acra`.`app` left join `acra`.`bug` on((`acra`.`bug`.`app_id` = `acra`.`app`.`id`))) left join `acra`.`report` on((`acra`.`report`.`bug_id` = `acra`.`bug`.`id`))) group by `acra`.`app`.`id`)]

**Comment by F43nd1r** [comment]
Thanks for reporting. As these views were removed again in the nexr change anyways, I just removed the changes.
