### ISSUE TITLE
HHH000315: Exception executing batch 

### ISSUE THREAD

**Issue by mortezarah** [F43nd1r/Acrarium#304]
this error happened:

ERROR 7 --- [           main] o.h.e.jdbc.batch.internal.BatchingBatch  : HHH000315: Exception executing batch [java.sql.BatchUpdateException: Duplicate entry 'ac55cop-Archos 55 Cobalt plus' for key 'PRIMARY'], SQL: insert into `device` (`marketing_name`, `device`, `model`) values (?, ?, ?)

and the Acrarium container restarting.

**Comment by F43nd1r** [comment]
are you using ACRARIUM_UPDATEDEVICELIST=true?
