### ISSUE TITLE
Startup crashes on debian 10 with java 11 main.changelog.kts is not a class

### ISSUE THREAD

**Issue by 0xpr03** [F43nd1r/Acrarium#306]
I can't reproduce this on a recent ubuntu. Only on a debian 10 box for some reason.
I'm also using a setup using -Duser.home= and only the default database config (mariadb 10.3)

Database is completely empty, crash log attached
[crash.log](https://github.com/F43nd1r/Acrarium/files/7422208/out.log)

**Comment by F43nd1r** [comment]
Acrarium requires Java 11

**Comment by 0xpr03** [comment]
Ok, that would make sense. Except it does work under java 1.8 on ubuntu and using java11 doesn't fix the problem. Same issue except now under java 11.

**Comment by F43nd1r** [comment]
The issue certainly looks weird. I recommend to just use the docker container.

**Comment by 0xpr03** [comment]
TBH I'm trying to avoid docker for its various problems in a VM setup. If everything fails I'll try to setup this with podman. But I'm actually interested to learn why the self-class-loading fails so hilarious.

**Comment by F43nd1r** [comment]
It fails because `com.faendirliquibase.changelog.v1_0_0.Main_changelog` is missing a dot (com.faendir.liquibase.changelog.v1_0_0.Main_changelog), now how that is possible I don't know.

**Comment by 0xpr03** [comment]
I can reproduce this with a clean debian 10 VM and the default openjdk-11-jre package. It works with the same setup in debian 11.

**Comment by 0xpr03** [comment]
I found the issue.
If you execute this as a user acra inside /acra without a home (/home/acra) it will always crash with that issue. Even on debian 11. Move that stuff into /home/acra and it'll be fine...

**Comment by 0xpr03** [comment]
I also had `ProtectHome=yes` enabled in the unit file

**Comment by F43nd1r** [comment]
Only thing that uses the home directory is loading application properties:
```kotlin
@PropertySources(PropertySource("classpath:default.properties"),
        PropertySource(value = ["file:\${user.home}/.config/acrarium/application.properties"], ignoreResourceNotFound = true),
        PropertySource(value = ["file:\${user.home}/.acra/application.properties"], ignoreResourceNotFound = true))
 ```

Might be an issue in spring, maybe see if you can reproduce with a blank spring app. Either way I don't see how I could fix this in acrarium
