### ISSUE TITLE
Acrarium crashing with SQLException

### ISSUE THREAD

**Issue by r748** [F43nd1r/Acrarium#309]
After upgrading my Acrarium version, I'm having the same error as already closed in issue [#307](https://github.com/F43nd1r/Acrarium/issues/307):

`Caused by: java.sql.SQLException: Incorrect string value: '\xE9\xA3\x9B\xE9\xA6\xAC...' for column 'marketing_name' at row 1`

I tried adding `command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']` to my docker-compose, but Acrarium still crashes during start. Any ideas on how to get Acrarium running again, without losing my existing database?

**Comment by F43nd1r** [comment]
You need to update the encoding of your existing tables to utf8mb4
