### ISSUE TITLE
Why is Acrarium SQL rather than NoSQL?

### ISSUE THREAD

**Issue by EmmanuelMess** [F43nd1r/Acrarium#31]
This question might make no sense, given that I'm not that experienced in setting up large data management systems. But it would seem to me that NoSQL would have better scalability.

**Comment by F43nd1r** [comment]
> Why is Acrarium SQL rather than NoSQL?

Very early versions use MongoDB, but I noticed quickly that relational databases are much easier to use when it comes to aggregating data for statistics.

> But it would seem to me that NoSQL would have better scalability

Maybe scalability would be increased by using a NoSql database. But functionality would be lost (or at least much harder to implement).

> I'm not that experienced in setting up large data management systems

Acrarium spawned from my own personal needs to have a better system than Acralyzer is, for my apps with a few thousand combined users. I did not build it with gargantuan systems in mind. However I do improve performance where I can, and as far as my tests go it behaves quite well under high load.
