### ISSUE TITLE
创建完项目，点击项目时报错

### ISSUE THREAD

**Issue by cuilingling** [F43nd1r/Acrarium#317]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bugTab' defined in URL [jar:file:/D:/devolep/Java/project/Acrarium/.config/acrarium/acrarium-1.6.1.jar!/BOOT-INF/classes!/com/faendir/acra/ui/view/app/tabs/BugTab.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.faendir.acra.ui.view.app.tabs.BugTab]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: java.net.URLDecoder.decode(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String;

**Comment by F43nd1r** [comment]
Acrarium requires Java 11, are you using an older jdk?

**Comment by 0xpr03** [comment]
使用中文翻译器：你必须使用java 11或以上版本，请尝试用英文报告问题。

**Comment by F43nd1r** [comment]
No further information and no english, closing.
