### ISSUE TITLE
Add basic security headers

### ISSUE THREAD

**Issue by otbutz** [F43nd1r/Acrarium#320]
Acrarium should set a few security related HTTP headers. By default the score of acrarium tested with tools like https://securityheaders.com isn't great.

We should at least set the following ones:

* `x-frame-options` to prevent clickjacking
* `Content-Security-Policy` to prevent XSS attacks

We could also replace the metatag introduced in #311 with the `x-robots-tag` header which is also supported by Google.

**Comment by otbutz** [comment]
`Strict-Transport-Security` would be nice but we would need to make sure that Acrarium is really accessed via HTTPS. Maybe as an opt-in via config flag?

**Comment by F43nd1r** [comment]
Sure, I can improve the defaults, but you should be able to set headers using spring security config https://docs.spring.io/spring-boot/docs/1.0.2.RELEASE/reference/html/common-application-properties.html

**Comment by F43nd1r** [comment]
Closing with [3a31975](https://github.com/F43nd1r/Acrarium/commit/3a31975451a600fb65c2a1582f3a78d61ea6fe1c). 
 - `Strict-Transport-Security` will be set based on the already existing spring property `security.require-ssl`
 - `Content-Security-Policy` cannot be set due to vaadin bootstrapping.
