### ISSUE TITLE
Cannot install Acrarium on AWS EC2 server

### ISSUE THREAD

**Issue by Timo1993** [F43nd1r/Acrarium#332]
I have to following problem: I would like to install Acrarium on an AWS EC2 server. I tried it but the server always does not respond after a short time (after executing the docker file). I installed docker and docker-compose and run it via docker-compose up. I get sometime the Acrarium logo but then it does not respond. I am also unable to connect to my server after executing the installation.

Do you have any idea how to fix it and what might cause this error?

**Comment by F43nd1r** [comment]
without any logs it's very hard to tell what's going on. 
perhaps the db connection can't be established?

**Comment by F43nd1r** [comment]
Closing because of no feedback.
