### ISSUE TITLE
[Feature Request] Filter reports by INSTALLATION_ID

### ISSUE THREAD

**Issue by gmk57** [F43nd1r/Acrarium#338]
ACRA assigns unique UUID for each app instance, see `ReportField.INSTALLATION_ID`. In Acrarium these IDs are shown in the report as "User". But we haven't found any way to view all reports from specific user.

Motivation: we're using ACRA for monitoring not only crashes, but also other abnormal situations. There may be thousands of reports. Having this filter would be very helpful in a number of cases, for example:
* investigate how often a problem occurs for a specific user
* perform a cross-check between ACRA reports and user complaints through other channels

Firebase Crashlytics has this functionality for a long time.

BTW, many thanks for ACRA & Acrarium! :)

**Comment by gmk57** [comment]
It might be even better to generalize this somehow, for example to be able to search/filter by "custom data" from `ACRA.getErrorReporter().putCustomData()`. In our specific case that would be more convenient (we put our own ID there), but not a deal-breaker. :)

**Comment by mikehardy** [comment]
Copying my just-about-perfectly-duplicate use case over here:

----
I checked the API class and I tried just constructing a URL but I can't see how to get all reports for a given ACRA install id, and this is actually my most common use case:

1- user logs an issue in our tracker, with debug info including their install ID
2- I want to go to acrarium or hit a URL/API via script with their install ID and pull stack traces

We have for example https://ankidroid.org/acra/app/1/bug/2651/report/3df33eb7-af8b-422a-b4c5-88a4ffa83c37

and in there, we have user 98814994-580a-48ca-b76d-4a40ea9ea6fa

But I don't see anything like https://ankidroid.org/acra/app/1/user/98814994-580a-48ca-b76d-4a40ea9ea6fa

Is this possible? Is this a feature request that's interesting for you and a PR would be welcome?
---

PRs appear to be welcome, with a simple addition to the API being a pretty easy start apparently

**Comment by mikehardy** [comment]
@F43nd1r you added this and released this while I was traveling so I did not have a chance to try it right after release. Today I had a request for user crash lookup by installation UUID though, so I thought it would be faster to drop the new jar in place and restart vs scrolling the old way and sure enough, this was fantastically easy to use. It Just Worked(tm). Thank you for adding this, it is now the most useful feature for us (other than accepting / warehousing the reports to begin with) :bow:
