### ISSUE TITLE
API documentation wanted

### ISSUE THREAD

**Issue by DerekDick** [F43nd1r/Acrarium#34]
Because the old Acralyzer is without a maintainer right now, and the new Acrarium is not production ready, our team want to implement the backend by ourselves. The question is we cannot find any **API documentation** for ACRA backend. Is there anything like this that can help us start?

BTW, thanks for your time to develop the open source ACRA!

**Comment by F43nd1r** [comment]
> our team want to implement the backend by ourselves

You've got several options for doing that:

- Using `acra-http`:
Your backend has to provide a url, which is either unprotected or uses basic http authentication.
This url has to accept either a json (preferred) or a form-url-encoded body, which is sent via either POST or PUT. 
Then you have to configure your acra app accordingly.
If you want to know how to parse a report, I recommend you inspect what acra sends. The basic format (for json) is 
```
{ 
REPORT_FIELD : value, 
ANOTHER_REPORT_FIELD: { complex_value_1: true, complex_value_2 : 42 }
}
``` 

- Using your own sender:
First define your API any way you like. Then implement and register a `ReportSender` which sends to your API in your acra app.

- Using existing projects:
Fork either Acralyzer or Acrarium and help to bring them to a stable and up to date version. 
I'd personally like to see you choose this option, as Acralyzer needs a maintainer and I am always happy about qualified help on Acrarium.

> the new Acrarium is not production ready

I'll probably update the disclaimer soon: I am using Acrarium in production myself, and it seems to work quite well. I still don't want to give any guarantees, but I haven't seen any data loss or corruption in the last few versions.

**Comment by DerekDick** [comment]
Thanks for your reply!

I finally decided to use Acralyzer for the time being. In the current stage of my project, I don't want to take over the maintenance job of Acralyzer because of the lack of spare time to finish this job. Of course, in the near future, I am willing to maintain the Acralyzer and make it better!
