### ISSUE TITLE
Development setup questions

### ISSUE THREAD

**Issue by 0xpr03** [F43nd1r/Acrarium#343]
I tried getting my hands dirty at #340, tiny checkbox focus area or the missing merge button for bugs. But as dumb as it sounds, I can't seem to get this project building.
What I did: Clone this repo, throw intellij at the directory and watch gradle download stuff for 5 minutes. Then it failed due to missing packages and intellij complained about missing definitions for various code in classes (others seemed fine).
```
Could not resolve org.xbib:time:2.1.0.
Required by:
    project :acrarium
```
I also tried setting the JDK version manually, but that lead to different issues.

What is the recommended setup for this ? (JDK,IDE setup..)

**Comment by F43nd1r** [comment]
I'm using JDK 11 with InteliiJ. You also need to build the project once to have all the querydsl sources generated

**Comment by 0xpr03** [comment]
Hm ok, I set the project bytecode to java11
```
Execution failed for task ':acrarium:kaptGenerateStubsKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':acrarium:kaptGenerateStubsKotlin'
   > Could not resolve all files for configuration ':acrarium:compileClasspath'.
      > Could not resolve org.xbib:time:2.1.0.
        Required by:
            project :acrarium
         > No matching variant of org.xbib:time:2.1.0 was found. The consumer was configured to find an API of a library compatible with Java 8, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
             - Variant 'apiElements' capability org.xbib:time:2.1.0 declares an API of a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
             - Variant 'runtimeElements' capability org.xbib:time:2.1.0 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java environment (preferred optimized for standard JVMs)
                     - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'jvm')
```

**Comment by F43nd1r** [comment]
your gradle still runs with jdk 8. There's a setting in intellij to use the project sdk for gradle.

**Comment by 0xpr03** [comment]
Thanks! This makes it work, especially the second one..
![grafik](https://user-images.githubusercontent.com/1280209/167727884-fa3b146b-2ee8-4a79-ae39-f88dbfed8ffa.png)
![grafik](https://user-images.githubusercontent.com/1280209/167727996-e2045ff3-cbc4-41ed-b5f9-fafc7b73476e.png)

**Comment by 0xpr03** [comment]
(And you have to set the same for kotlin. Seems like intellij still uses the lowest available JDK for everything on my system.)

**Comment by 0xpr03** [comment]
I still get this issue
![grafik](https://user-images.githubusercontent.com/1280209/167728489-b2252bef-449f-4fa7-835e-5b8d9cde1d78.png)

**Comment by 0xpr03** [comment]
Ok something doesn't like me, I can run it but when I go to the login page I get encoding errors !? This is the same system I can just run the release java file.
```
javax.servlet.ServletException: com.vaadin.flow.server.ServiceException: java.nio.file.InvalidPathException: Illegal char <
> at index 12: lit-element'

@customElement("acrarium-box")
export default class Box extends LitElement {
    static get styles() {
        return css`
                :host {
                    display: fle
	com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:301)
	com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:109)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
```

**Comment by F43nd1r** [comment]
Never seen that before. I usually develop on linux but it shouldn't matter, so yeah...

**Comment by 0xpr03** [comment]
Yeah I'll give it a go on linux tomorrow.
