### ISSUE TITLE
Is there some way (URL, or API) to get reports for a specific install/user?

### ISSUE THREAD

**Issue by mikehardy** [F43nd1r/Acrarium#346]
Hey @F43nd1r :wave: 

I checked the API class and I tried just constructing a URL but I can't see how to get all reports for a given ACRA install id, and this is actually my most common use case:

1- user logs an issue in our tracker, with debug info including their install ID
2- I want to go to acrarium or hit a URL/API via script with their install ID and pull stack traces

We have for example https://ankidroid.org/acra/app/1/bug/2651/report/3df33eb7-af8b-422a-b4c5-88a4ffa83c37

and in there, we have user 98814994-580a-48ca-b76d-4a40ea9ea6fa

But I don't see anything like https://ankidroid.org/acra/app/1/user/98814994-580a-48ca-b76d-4a40ea9ea6fa

Is this possible? Is this a feature request that's interesting for you and a PR would be welcome?

**Comment by F43nd1r** [comment]
There is the export functionality which does this, not sure if that helps your use case. I'm happy to accept pull requests extending `RestApiInterface`

**Comment by mikehardy** [comment]
I think having it be in the UI would be ideal (that is, a URL to hit) with an API I could hit via a curl request or similar being second best (and, not too hard to implement).

I'll see if it's something I can do + I will check for interest among the AnkiDroid devs.

**Comment by F43nd1r** [comment]
Yeah sure I mean if you want to do the UI that works as well, I just don't have the time for it and extending the rest API is leagues easier.

**Comment by gmk57** [comment]
Looks similar to #338
It would be great if anybody can add this functionality.

**Comment by mikehardy** [comment]
@gmk57 sorry I did not see that one, this is duplicate really, apologies. I posted it up on our ankidroid dev channel and did not have any takers yet but you never know... - resolving as duplicate and I'll post over on that issue
