### ISSUE TITLE
Can't upload mapping file

### ISSUE THREAD

**Issue by r748** [F43nd1r/Acrarium#347]
Using version 1.7.0 when trying to upload a 40 MB mapping file, the upload progress shows, but after completion I get an error message "Server unavailable". When I upload a smaller file, everything works fine.

I set `command: --max_allowed_packet=128M` in my database config hoping this would resolve the issue, but upload still fails. Any ideas?

Edit: The logs don't show any error btw!

**Comment by F43nd1r** [comment]
Please test if you can upload mappings via API rest call

**Comment by r748** [comment]
Thanks, this really helped me find the problem!!

I wasn't aware the mapping file could be uploaded via API. Trying to do this with Postman returned the nginx error `413 Request Entity Too Large`. By setting `client_max_body_size 100M;` in my nginx.conf, the upload now works both via API and through the Acrarium web interface.
