### ISSUE TITLE
Explain how to deploy a war

### ISSUE THREAD

**Issue by sergeygindin** [F43nd1r/Acrarium#35]
Explain please, how to build a war file and where, for not experienced users.

**Comment by sergeygindin** [comment]
Second, i get an error after compiling and deploying.
The tomcat returns Application at context path [/acra] could not be started
Exception ocurred - [org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/acra]]]

**Comment by sergeygindin** [comment]
Also i'm having an error in logs, connecting to DB for root@localhost. Explain, normally, where should i set the application.properties to?

**Comment by sergeygindin** [comment]
It seems like the application.properties file is not reading by tomcat. 
The application.properties is located under /opt/tomcat/.acra
The application itself located at /opt/tomcat/webapps/acra/

**Comment by F43nd1r** [comment]
Just download the latest release https://github.com/F43nd1r/Acrarium/releases

If you want to build the war yourself, run the respective gradle task.
