### ISSUE TITLE
Possibility of Including swagger-ui for the API

### ISSUE THREAD

**Issue by dosindi** [F43nd1r/Acrarium#373]
Is it possible to Include swagger-ui to enhance documentation for the API ?

**Comment by F43nd1r** [comment]
https://github.com/F43nd1r/Acrarium/wiki/Optional-features#swagger-api-documentation (1.9 currently unreleased)

**Comment by dosindi** [comment]
Thanks for enhancement
Kindly confirm if this is the correct swagger API doc url
https://example.com/actuator/swagger-ui/swagger-ui.html

**Comment by F43nd1r** [comment]
probably not, you need to use a different port as explained in the docs.  Also the swagger-ui.html is redundant
