### ISSUE TITLE
[Fedora] docker-compose up throws numerous errors

### ISSUE THREAD

**Issue by Doomsdayrs** [F43nd1r/Acrarium#378]
Log right here, I am a bit confused on what is going on
[acrarium-error-2022-09-06.txt](https://github.com/F43nd1r/Acrarium/files/9502508/acrarium-error-2022-09-06.txt)

**Comment by F43nd1r** [comment]
Looks like your docker and/or system install is broken. Nothing related to acrarium in there

**Comment by Doomsdayrs** [comment]
Solution was to ensure docker was enabled and running via systemctl
