### ISSUE TITLE
Acrarium On DigitalOcean Marketplace

### ISSUE THREAD

**Issue by ZdenkoRufati** [F43nd1r/Acrarium#38]
What do you think of putting Acrarium into the [DigitalOcean marketplace](https://marketplace.digitalocean.com/)? 
That would simplify the ACRA setup for hosting noobs like me. 😅

**Comment by F43nd1r** [comment]
Honestly, I don't have any plans to bring this project to any kind of platform.

Acrarium was spawned by my personal need for a better acra backend than Acralyzer.
I've made it available as is, so other people can use it as well. But I don't want to spend the time to learn the specifics of platforms like digitalocean. If someone else wants to do the work, I'll gladly link to it.

**Comment by F43nd1r** [comment]
acrarium now has a docker container released, which simplifies the setup to a 3 step process and as a sideeffect should allow running it on platforms like digitalocean, which support docker.
