### ISSUE TITLE
Alias for Custom Columns

### ISSUE THREAD

**Issue by Backfisch145** [F43nd1r/Acrarium#380]
### The Problem
When creating a custom column, the json-path is used as the name of the column.
This behavior can lead to an ugly and confusing table head, when looking at your reports.
### Solution
Adding the opportunity to set an alias for the custom column, which is then shown in the table head instead of the raw json-path.

**Comment by F43nd1r** [comment]
Part of https://github.com/F43nd1r/Acrarium/releases/tag/v2.0.0-alpha01
