### ISSUE TITLE
Feature request: Close bugs on reports page

### ISSUE THREAD

**Issue by r748** [F43nd1r/Acrarium#381]
When having several similar bugs in the overview list (/app/x/bug) I sometimes find it hard to keep track of which bug is the right one to close, because the list only shows an abbreviated title (e.g. java.lang.NullPointerException: Attempt to read from field 'an...). Therefore it would be helpful to have an option to close a bug from the reports page (/app/x/bug/xxxx/report). Alternatively, showing the bug id in the overview list (e.g. on hover over an entry) would also make it easier to identify the correct report to close.

**Comment by F43nd1r** [comment]
Included in https://github.com/F43nd1r/Acrarium/releases/tag/v2.0.0-alpha01
