### ISSUE TITLE
Support Application Flavors

### ISSUE THREAD

**Issue by otbutz** [F43nd1r/Acrarium#388]
![image](https://user-images.githubusercontent.com/22315436/194001167-bb368a7a-7619-40bb-bfe3-b3f905b65a70.png)

The summary should report `3.6.6 22-09-14 Trinks-SW Prod` which is the version in the details below.

We deploy one app with multiple product flavors. Maybe that's causing this problem?

**Comment by otbutz** [comment]
This can happen because the version code is based on a timestamp: `YYYY MM DD HH`. But these apps still have different applicationIds and therefore are treated as different apps since they contain custom branding, etc.

Would it be advisable to create different Acrarium projects for them? Since they share well over 90% of the codebase, it made sense from our perspective to keep them together.

**Comment by F43nd1r** [comment]
I have not considered flavors before. Use it how it suits you best, and I'll keep this around as enhancement

**Comment by F43nd1r** [comment]
Could you let me know if the flavor is available somewhere in your reports outside of the name?

**Comment by otbutz** [comment]
Will check :wink:

**Comment by otbutz** [comment]
The best spot to differentiate should be the package name. This identifier is fully unique per app. The combination of package name and version code should be the safest choice.

**Comment by F43nd1r** [comment]
I'm leaning towards using BuildConfig.FLAVOR

**Comment by F43nd1r** [comment]
Included in https://github.com/F43nd1r/Acrarium/releases/tag/v2.0.0-alpha01
