### ISSUE TITLE
How to start after deployment?

### ISSUE THREAD

**Issue by IchoTolot** [F43nd1r/Acrarium#39]
Hello,
I know your time is precious, but unfortunately I can't find a solution on the net.
I have deployed the war from 0.71 successfull on my tomcat. Since i'm not very familiar with tomcat, I installed the tomcat sample application. 
After that, there is an index.html under /webapps/sample which i can also access under http://xx.xx.de/sample.index.html

Which file do I have to call for acrarium?
There is no index.html neither a web.xml in WEB-INF

Thanks in advance.
Tolotos

**Comment by F43nd1r** [comment]
No need to call any file, just navigate to the context url. E.g. `example.com/acra/`

**Comment by IchoTolot** [comment]
Did so and it gave a 404 :-(
I can write my own web.xml but which servlet do I have to call first?
