### ISSUE TITLE
No charts in "Statistics"

### ISSUE THREAD

**Issue by st4141** [F43nd1r/Acrarium#394]
I am trying Acrarium today and just succeed to upload some crash reports.
The Statistics page is empty. Is this a bug or did I miss something ?
I am using Acrarium Docker Latest = "Running version 1.9.0-beta01"

![Screenshot_20221104_123943](https://user-images.githubusercontent.com/18347703/199964554-af21fe9f-18e1-4e5d-a5ac-aca7ae5d4eea.png)
![Screenshot_20221104_123953](https://user-images.githubusercontent.com/18347703/199964557-5dec6766-8b2e-4d74-8bbf-76c9a55b49ee.png)

**Comment by st4141** [comment]
I just tryed 1.8.1. It works

![Screenshot_20221104_124523](https://user-images.githubusercontent.com/18347703/199965153-77f61286-0e63-4ec5-aafe-537ec4f90be6.png)

**Comment by F43nd1r** [comment]
Well, "works" yes. "works as intended" no. You should only have one instance of the bar graph. I shuffled a few things around so I'd hope this will be solved with v2.0
