### ISSUE TITLE
BugDataProvider NullPointerException

### ISSUE THREAD

**Issue by otbutz** [F43nd1r/Acrarium#395]
Acrarium 1.9.0-beta01

![image](https://user-images.githubusercontent.com/22315436/200779842-b3f87285-05b7-4102-bc9d-ce8c49370305.png)

**Comment by otbutz** [comment]
Same symptoms as described in https://github.com/F43nd1r/Acrarium/issues/301#issuecomment-1197931294

**Comment by F43nd1r** [comment]
Should be solved with 2.0.0
