### ISSUE TITLE
Database connection leak

### ISSUE THREAD

**Issue by otbutz** [F43nd1r/Acrarium#398]
![image](https://user-images.githubusercontent.com/22315436/203499964-4d054e88-5299-4089-862d-3180f4164ea7.png)

**Comment by otbutz** [comment]
Is it possible to tune the size of the pool?

**Comment by otbutz** [comment]
@F43nd1r Any tips for investigation?

**Comment by F43nd1r** [comment]
As I'm in the process of switching out the whole database layer for Acrarium 2, I'd hope this issue will be gone then.

**Comment by F43nd1r** [comment]
I'm closing this until it is confirmed to exist in 2.0.0
