### ISSUE TITLE
Error occured when uploading a proguard mapping file

### ISSUE THREAD

**Issue by glzlaohuai** [F43nd1r/Acrarium#40]
I followed the guide to setup Acrarium on my local tomcat server, and it truly worked well. But when I tried to upload a proguard mapping file, I was prompted this error: "Unexpected Server Error". 
I have no server-side background knowledge, so can't figure out this is something I need to do on my local test environment or an issue.

**Comment by F43nd1r** [comment]
Which version were you using?

**Comment by F43nd1r** [comment]
Stale - closing
