### ISSUE TITLE
Android Studio Integration

### ISSUE THREAD

**Issue by Doomsdayrs** [F43nd1r/Acrarium#408]
With Android Studio Electric Eel, Android Studio is able to retrieve crash information from Firebase Crashlytics.

It would be nice to have an extension that integrates with it to retrieve information from Acrarium instead.

**Comment by F43nd1r** [comment]
While this is a nice idea, it is also pretty big. Don't think I have the time for it. If someone wants to give it a try, the rest api exists already and could be easily extended if something is missing.
