### ISSUE TITLE
UI questions

### ISSUE THREAD

**Issue by federicoiosue** [F43nd1r/Acrarium#416]
Hi there, 

thanks for the great app, I moved to this from Tracepot but I due to the desire to provide users with a completelly FOSS stack for transparency this really fitted my needs.

Here's my instance, publically accessible with guest/guest credentials: https://acra.omninotes.app

A couple of considerations after some days of (light) usage:

- Could be useful to have "hover" effect while moving through tables' entries
- Same way as before having a "click" graphical feedback would be nice: sometimes I click on things and I really don't have the perception that something is happening or not
- "Solved" drop-town-menu would be really useful also into the bug detail section: I found not a way to mark issue as solved from inside its detailed view

**Comment by F43nd1r** [comment]
Hi, looking at your instance it seems like you're running v1.8. As I recently released v2 alpha all feature requests/improvements should be based on that.
Please verify that the mentioned issues still exist in the latest version and state your version in future reports.

**Comment by federicoiosue** [comment]
Sorry, I assumed I was using the latest version 1.8.1.
I'm going to give a look at latest alpha version, thanks!

**Comment by F43nd1r** [comment]
I improved styles according to your first two points. Your third point is already solved with #381
Release 2.0.0-alpha02 will go out in a minute.
