### ISSUE TITLE
No UI mode

### ISSUE THREAD

**Issue by federicoiosue** [F43nd1r/Acrarium#429]
Hi there, 

I'm using the currently stable version 1.8.1 on a VPS with really low resources. Just to give you an idea this is the resources usage at the moment I'm writing:

`730 root      20   0 2458744 377656   4896 S  99.3  43.2  30:34.39 java`

Due to this the user interface is actually useless, I can't even access to reports. This is actually happening since the reports number become larger (maybe after 3k reports).
So I started using just by accessing the database with a client (the database is elsewhere, so it's not afflicted by performances dropdown) but I saw that also an [API-access mode](https://github.com/F43nd1r/Acrarium/wiki/Optional-features#api-access) is available so I'll give a look at it.

My question was about the following: is there a way to disable the frontend bootstrap to let to the backend all the available resources on that VM?

Thanks!

**Comment by F43nd1r** [comment]
You should be able to set `vaadin.loadOnStartup` to `false` in your configuration, which should delay frontend loading until first access
