### ISSUE TITLE
set basicAuthLogin  and basicAuthPassword when create a project manually

### ISSUE THREAD

**Issue by amira133** [F43nd1r/Acrarium#484]
Hello,
I had previously set up an `Acrarium server` and created several projects on it. Unfortunately, that server went offline. Now, I've restarted the server and want to recreate the projects. However, the system automatically fills in the values for `basicAuthLogin` and `basicAuthPassword`. Therefore, I am looking for a method to manually configure these values. Is there a way to do this?

**Comment by F43nd1r** [comment]
If you still have the old database you should be able to copy the old values over. Otherwise you'll have to bcrypt-hash the password yourself.
In either case this isn't an intended functionality so be careful not to break foreign key relations and the like
