### ISSUE TITLE
Update standalone setup

### ISSUE THREAD

**Issue by phhusson** [F43nd1r/Acrarium#49]
Create database line should be :

`CREATE DATABASE CHARACTER SET utf8;` otherwise some distributions will report `Index column size too large. The maximum column size is 767 bytes.`

config file database line sbould be:
`spring.datasource.url=jdbc:mysql://localhost:3306/acrarium?useSSL=false`

On my distribution, I had to change to `GRANT ALL PRIVILEGES ON acrarium.* TO acrarium;` but i'm not sure why.

**Comment by F43nd1r** [comment]
You should be able to update the wiki yourself.

**Comment by phhusson** [comment]
Oops my bad, I swear I did look for it.

**Comment by F43nd1r** [comment]
Thank you for your contribution :+1:
