### ISSUE TITLE
Can't auto-start Acrarium on reboot

### ISSUE THREAD

**Issue by aloz77** [F43nd1r/Acrarium#495]
After basic setup on Debian 11 according to https://github.com/F43nd1r/Acrarium/wiki/Setup-guide I can start/stop Acrarium by these commands without issues.

```
docker-compose up -d
docker-compose stop
```

However if machine is rebooted on the next restart I encounter a situation that mysql isn't started and acrarium keeps restarting.

```
# docker ps -a
CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS                                  PORTS                    NAMES
b53a07c38f78   f43nd1r/acrarium:latest        "/bin/sh -c 'java or…"   3 minutes ago    Restarting (1) Less than a second ago                            acrarium
d55549868ecf   mysql:5.7                      "docker-entrypoint.s…"   44 minutes ago   Exited (0) About a minute ago                                    database
```

Any idea how to fix it?

**Comment by F43nd1r** [comment]
acrarium will restart until the db is available I guess. You'd have to check the container logs of the db to see what is going on.

**Comment by F43nd1r** [comment]
I'm using external db as well, not too confident in the behaviour of dockerized mysql. Probably could add a restart statement there to fix it as well, but if you found a solution that works for you, great.
