### ISSUE TITLE
POST with gzip?

### ISSUE THREAD

**Issue by haamaanaa** [F43nd1r/Acrarium#5]
Hi! Does Acrarium accept gzip request payload compression?

I'm testing ANR reporting to acrarium backend and traces.txt can be close to 1 MB size of plain text. Would be nice to compress that over the network.

**Comment by F43nd1r** [comment]
I don't think it is supported out of the box, and I didn't implement anything.

**Comment by F43nd1r** [comment]
Honestly, I'm quite surprised it never came up to use compression in ACRA. I'll probably add an option for it in the next version

**Comment by haamaanaa** [comment]
There is something about gZip mentioned in:

https://github.com/F43nd1r/Acrarium/blob/master/src/main/java/com/faendir/acra/rest/RestConfiguration.java

Does that mean it would actually be available already?

**Comment by F43nd1r** [comment]
Currently, Acrarium can accept gzip (but only in the upcoming release). 

Acra-http cannot send gzip yet (but will be able to when ACRA/acra#674 is merged)
