### ISSUE TITLE
Question: HTTPS support?

### ISSUE THREAD

**Issue by andreas-borglin** [F43nd1r/Acrarium#50]
Hi there.

Thanks for a useful tool. I can't however find any information about HTTPS support? As of Android API level 28, HTTP (clear text) is disabled by default and it's of course not a good idea to send any information off a device in clear text. ACRA itself supports HTTPS - is this supported by Acrarium or are there plans to support it?

Thanks in advance

**Comment by F43nd1r** [comment]
Https support is not an application level problem. 
If your web server supports https, Acrarium will too.
Most web servers support https, including tomcat, which is bundled in the docker image.
