### ISSUE TITLE
Docker ARM Image

### ISSUE THREAD

**Issue by PaulWoitaschek** [F43nd1r/Acrarium#51]
I'm trying to install acdrarium on a raspberry pi.
When starting the container, it quits with an error:
`ERROR: no matching manifest for linux/arm/v7 in the manifest list entries`

Could you publish an arm v7 image?

**Comment by F43nd1r** [comment]
Architecture is set in the [dockerfile](https://github.com/F43nd1r/Acrarium/blob/master/acrarium/Dockerfile#L1) by the base image. I did't find any openjdk docker images including armv7. 

I recommend using tomcat directly. On a system with very limited resources you'll appreciate the performance gain of a direct install as well.
