### ISSUE TITLE
v2 migration failure

### ISSUE THREAD

**Issue by Doomsdayrs** [F43nd1r/Acrarium#512]
Version: v2.0.0-beta09

## Reason

```
Reason: liquibase.exception.DatabaseException: Duplicate column name 'report_count' [Failed SQL: (1060) ALTER TABLE acrarium.bug ADD report_count INT DEFAULT 0 NULL, ADD latest_report datetime NULL, ADD solved_version_code INT NULL, ADD solved_version_flavor VARCHAR(255) NULL, ADD latest_version_code INT NULL, ADD latest_version_flavor VARCHAR(255) NULL, ADD affected_installations INT DEFAULT 0 NULL]
```

## Error Log
[error.log](https://github.com/F43nd1r/Acrarium/files/14746557/error.log)

## Notes

I hope this is done in a transaction!

**Comment by F43nd1r** [comment]
what was your previous version?

**Comment by Doomsdayrs** [comment]
> what was your previous version?

I believe it was: `v1.8.1`

Then I loaded  `v2.0.0-beta07` when ` v2.0.0-beta08` failed to run.
After which the error occurred.

Persists in upgrade to `v2.0.0-beta09`.

**Comment by Doomsdayrs** [comment]
With a fresh database, the issue persists, but with a helpful(?) log.

```
Reason: liquibase.exception.DatabaseException: You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable) [Failed SQL: (1419) CREATE TRIGGER bug_report_insert AFTER INSERT ON `report` FOR EACH ROW CALL update_bug_report_stats(NEW.`bug_id`)]
```

**Comment by F43nd1r** [comment]
I haven't taken the time to update the setup guide for v2. You need `--log-bin-trust-function-creators`

**Comment by Doomsdayrs** [comment]
> I haven't taken the time to update the setup guide for v2. You need `--log-bin-trust-function-creators`

Sorry for the late reply, this did fix it!~
