### ISSUE TITLE
Setup page doesn't save user

### ISSUE THREAD

**Issue by F43nd1r** [F43nd1r/Acrarium#59]
> after filling setup page, click to confirm and see setup page again. I cannot go to next step.
Setup from docker-compose

See https://github.com/F43nd1r/Acrarium/issues/55#issuecomment-634068739

**Comment by F43nd1r** [comment]
It did actually save the user, but a cache issue prevented the application froim seeing it.

**Comment by HeyItsMeNobody** [comment]
Thank you! Can't wait to try ACRA out with this interface. Just have to wait on the Docker hub update now.

**Comment by F43nd1r** [comment]
@HeyItsMeNobody Docker Hub has very fast response times. Releases should be available within 5-10 Minutes after I push them.
