### ISSUE TITLE
Nothing showing up in the Bugs tab

### ISSUE THREAD

**Issue by HeyItsMeNobody** [F43nd1r/Acrarium#60]
I'm not sure if this is a problem with ACRA or with Acrarium, And I might just be stupid. I have set up ACRA correctly and it shows in logcat that it has caught an exception. I can also clearly see that it is inserting stuff into the database in the Acrarium logs. 
![Screenshot 2020-05-26 at 7 25 50 PM](https://user-images.githubusercontent.com/40901726/82931148-bb98aa80-9f86-11ea-9883-6f856daa1ef7.png)

I'm probably just doing something wrong, But thought to report it here anyways since I can't find anything in the documentation.

**Comment by F43nd1r** [comment]
Please don't post logs in images, use

    code blocks.

Those logs are only showing selects, no inserts.
Did you refresh the page? Acrarium has no live updating.

**Comment by HeyItsMeNobody** [comment]
I have realized that ACRA is probably not sending anything as the Acrarium log doesn't show any inserts. So this probably is the wrong place for this error. Would the HTTP sender URI being HTTPS be a problem? I followed the BasicSetup but that is all I changed.

**Comment by F43nd1r** [comment]
https is fully supported on both sides. Acra will log a message when it fails to send a report.
But I think it is a server side problem, as I've just tried to submit to a new instance and got a database exception.

**Comment by HeyItsMeNobody** [comment]
ACRA isn't logging anything, Only that it caught an Exception to send. Thank you for your awesome help, If only we had people like you for iOS.

**Comment by F43nd1r** [comment]
Should be fixed in 155bfadcb8ce89f0a18d80e46f6eea31ea04e465 released as 0.10.7

**Comment by HeyItsMeNobody** [comment]
Thank you! Everything is working properly now. Hope better support for smaller screens is added soon.

**Comment by F43nd1r** [comment]
Which issues do you have on smaller screens? Acrarium is intended as desktop application, so no plans to change the UI.

**Comment by HeyItsMeNobody** [comment]
Hello @F43nd1r, The issues I was talking about was things like cut-off buttons and general bad visibility (Like things being too big). And the stacktrace being cut off.
![Screenshot 2020-05-27 at 12 32 02 PM](https://user-images.githubusercontent.com/40901726/83008925-41176b80-a016-11ea-904c-72e2e5eed0e2.png)

**Comment by F43nd1r** [comment]
The cut-off button only happens when the grid is empty. It is probably an issue for upstream ([vaadin grid flow](https://github.com/vaadin/vaadin-grid-flow) or [vaadin grid](https://github.com/vaadin/vaadin-grid)), but I consider it very low priority, as the button isn't needed when the grid is empty. I guess I could hide it in that case.

Which things are too big in your opinion?
I have not seen any cut-off for stacktraces, please share a screenshot.
