### ISSUE TITLE
load js returncode 404

### ISSUE THREAD

**Issue by CarlTien** [F43nd1r/Acrarium#7]
failed to load widgetset ./VAADIN/widgetsets/com.faendir.acra.AppWidgetset/com.faendir.acra.AppWidgetset.nocache.js?1529036824635 404

**Comment by CarlTien** [comment]
when i enter /acra , it just alert this "failed to load widgetset ./VAADIN/widgetsets/com.faendir.acra.AppWidgetset/com.faendir.acra.AppWidgetset.nocache.js?1529036824635"

**Comment by F43nd1r** [comment]
Are you compiling from source? If so, run 
`vaadinCompileWidgetset`
 and `vaadinCompile` once

**Comment by F43nd1r** [comment]
If not, which version are you using?

**Comment by CarlTien** [comment]
gradle vaadinCompileWidgetset not found

**Comment by F43nd1r** [comment]
Correction, the tasks are called `vaadinThemeCompile` and `vaadinCompile`

**Comment by CarlTien** [comment]
thank u
