### ISSUE TITLE
Standalone with existing database, run using java -jar not working

### ISSUE THREAD

**Issue by aravindarc** [F43nd1r/Acrarium#74]
the following was run:
`java -jar acrarium-0.10.7.war `

which resulted in an error of:
`no main manifest attribute, in acrarium-0.10.7.war`

**Comment by courville** [comment]
Same here.
Only version that works for me (`openjdk-11-jdk:armhf`) is 0.9.22... quite an old one.
Desperate, I even tried this (but is not stable at all):
```
jar -xvf acrarium-0.10.7.war
java -classpath "./WEB-INF/lib/*:./WEB-INF/classes/." com.faendir.acra.BackendApplicationKt
```

**Comment by F43nd1r** [comment]
Yeah, the build process has changed a bit. You need the jar, not the war. I've updated the latest release with the file and all future releases will include them as well. Wiki is updated as well.

**Comment by deva-gopalani** [comment]
@F43nd1r hey i had a question... I have run the jar file of acrarium on my remote server. I am not able to get the crash logs of more than one project. How could this be resolved?

**Comment by F43nd1r** [comment]
@deva-gopalani please don't highjack old issues. You need to create one "app" inside acrarium for each project, using the given respective configuration in your android projects.
