### ISSUE TITLE
[Question] Acrarium or Acralyzer

### ISSUE THREAD

**Issue by HulakOleksandr** [F43nd1r/Acrarium#88]
Hi there!

I am about to start using ACRA as a crash reporting system, data and backend will be stored on my own server. What would you recommend to go with - Acrarium or Acralyzer? 
I am more inclined to Acrarium, but the "This project is expected to enter stable phase soon" message was posted eight months ago. How unstable it is?

**Comment by F43nd1r** [comment]
I'm only holding back stable release because Acrarium requires Vaadin 17, which is itself in Alpha. Vaadin 17 is scheduled for stable release in september and this project will follow soon after.
I am not aware of any issues with the project, but I haven't done rigorous testing either.

**Comment by HulakOleksandr** [comment]
Thank you for the explanation!
